title: SeCeRiTyRaBbiT.com =o\=o\=o\>
description: Always hacking at something, rabbitear's thoughts and notes about free software, computer security, and the random.
google_analytics: 
show_downloads: true
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
  - jekyll-sitemap

