title: SeCeRiTyRaBbiT blog
description: Always hacking at something, may as well share some notes -- rabbitear.
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
