title: PapeRRaBbiT.com =o\=o\=o\>
description: Always hacking at something, rabbitear's thoughts and notes about free software, computer security, and the random.
google_analytics: 
show_downloads: true
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-hacker

plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed

jekyll-mentions:
  base_url: https://twitter.com

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
